// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDqnvj-3rqOS0aeSf2nGNxV6nUeHDAbY',
    appId: '1:680298830709:web:226e9f7ca553ebd00a513c',
    messagingSenderId: '680298830709',
    projectId: 'db-miner-bf0f9',
    authDomain: 'db-miner-bf0f9.firebaseapp.com',
    storageBucket: 'db-miner-bf0f9.appspot.com',
    measurementId: 'G-S6VSN8LBQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOBR6wGcdAzUMqT6iiye_Th4OYuShh5I',
    appId: '1:680298830709:android:2e8e3233378e88b10a513c',
    messagingSenderId: '680298830709',
    projectId: 'db-miner-bf0f9',
    storageBucket: 'db-miner-bf0f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vPZiz2yr6lzdQ6XJlcQTgNIpkynH2hE',
    appId: '1:680298830709:ios:8c2efb9aebe1559d0a513c',
    messagingSenderId: '680298830709',
    projectId: 'db-miner-bf0f9',
    storageBucket: 'db-miner-bf0f9.appspot.com',
    iosBundleId: 'com.example.dbMinerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vPZiz2yr6lzdQ6XJlcQTgNIpkynH2hE',
    appId: '1:680298830709:ios:a58f7a588f1c77a60a513c',
    messagingSenderId: '680298830709',
    projectId: 'db-miner-bf0f9',
    storageBucket: 'db-miner-bf0f9.appspot.com',
    iosBundleId: 'com.example.dbMinerFirebase.RunnerTests',
  );
}
